#!/usr/bin/env python3
"""CLI entry point for the Plan-It SDK.

Provides the ``plan-it`` command for starting the server, checking the
environment, and running diagnostics across macOS, Windows, Linux, iOS,
and Android installations.
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import subprocess as _subprocess

from app.env_detect import Environment, check_environment, format_env_report

logger = logging.getLogger("plan-it.cli")

_ASCII_LOGO = r"""
   ██╗███████╗███████╗███████╗ ██████╗ ███████╗
   ██║██╔════╝██╔════╝██╔════╝██╔═══██╗██╔════╝
   ██║█████╗  █████╗  █████╗  ██║   ██║███████╗
██  ██║██╔══╝  ██╔══╝  ██╔══╝  ██║   ██║╚════██║
╚████╔╝███████╗██║     ██║     ╚██████╔╝███████║
 ╚═══╝ ╚══════╝╚═╝     ╚═╝      ╚═════╝ ╚══════╝
   Plan-It  v0.3.0
"""


def _find_env_file(env: Environment) -> Path | None:
    """Locate the .env file using a platform-aware search order."""
    # 1. Explicit TRAVEL_ENV_PATH
    explicit = os.environ.get("TRAVEL_ENV_PATH")
    if explicit and Path(explicit).is_file():
        return Path(explicit)

    # 2. Current directory
    cwd_dotenv = Path.cwd() / ".env"
    if cwd_dotenv.is_file():
        return cwd_dotenv

    # 3. Package data directory (installed via pip)
    pkg_dotenv = Path(__file__).resolve().parent.parent / ".env"
    if pkg_dotenv.is_file():
        return pkg_dotenv

    # 4. Home directory config
    if env.system == "darwin":
        candidates = [
            Path.home() / ".config" / "plan-it" / ".env",
            Path.home() / "Library" / "Application Support" / "plan-it" / ".env",
        ]
    elif env.system == "windows":
        candidates = [
            Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming")) / "plan-it" / ".env",
            Path.home() / ".plan-it" / ".env",
        ]
    else:  # linux / android / ios
        candidates = [
            Path.home() / ".config" / "plan-it" / ".env",
            Path.home() / ".plan-it" / ".env",
        ]

    for cand in candidates:
        if cand.is_file():
            return cand

    return None


def _bootstrap_dotenv(env: Environment) -> Path:
    """Copy .env.example to the appropriate platform location and return the
    path to the new .env file."""
    example = Path(__file__).resolve().parent.parent / ".env.example"
    if not example.is_file():
        # Try relative to package
        example = Path(__file__).resolve().parent.parent / ".env.example"

    if env.system == "darwin":
        config_dir = Path.home() / ".config" / "plan-it"
    elif env.system == "windows":
        config_dir = Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming")) / "plan-it"
    else:
        config_dir = Path.home() / ".config" / "plan-it"

    config_dir.mkdir(parents=True, exist_ok=True)
    dest = config_dir / ".env"

    # Check if we have the example file embedded as a resource
    if example.is_file():
        shutil.copy2(example, dest)
    else:
        # Fallback: write a minimal .env from the embedded defaults
        dest.write_text(
            "# Plan-It — Environment Configuration\n"
            "# Generated by plan-it init\n"
            "# No API keys required — fully self-contained\n\n"
            "TRAVEL_API_KEY=\n"
            "RATE_LIMIT=10/minute\n"
            "CORS_ORIGINS=*\n"
            "# Search: ddg (DuckDuckGo), searxng (SearxNG), or auto (DDG first, failover to SearxNG)\n"
            "SEARCH_BACKEND=auto\n"
            "# SearxNG instance URL (public or self-hosted)\n"
            "SEARXNG_INSTANCE=https://searx.be\n"
            "SEARCH_MAX_RESULTS=12\n"
            "SEARCH_RATE_LIMIT_S=1.2\n"
            "MAX_INPUT_LENGTH=2000\n"
            "ENVIRONMENT=production\n"
            "TRAVEL_HOST=0.0.0.0\n"
            "TRAVEL_PORT=8000\n"
        )

    return dest


def cmd_init(args: argparse.Namespace) -> int:
    """Bootstrap the environment for a new installation."""
    env = check_environment()
    print(_ASCII_LOGO)
    print(format_env_report(env))

    dotenv = _find_env_file(env)
    if dotenv:
        print(f"\n✓ Found existing .env: {dotenv}")
    else:
        print("\nNo .env file found — bootstrapping from template...")
        dotenv = _bootstrap_dotenv(env)
        print(f"✓ Created .env at: {dotenv}")

    print("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("  No API keys needed — this app is fully self-contained.")
    print("  Configuration file:")
    print(f"    {dotenv}")
    print()
    print("  Start the server:")
    print("    plan-it serve")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    return 0


def _detect_lan_ip() -> str | None:
    """Detect the primary LAN IP address for sharing with beta testers.

    Connects a UDP socket to a public address (no data sent) and inspects
    the local address assigned by the OS. Returns None if unreachable.
    """
    import socket
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(0.5)
        # 8.8.8.8 is Google DNS — we never send data, just use it to
        # discover the routable local interface address
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return None


def _start_cloudflare_tunnel(port: int) -> subprocess.Popen | None:  # type: ignore[valid-type]
    """Launch a Cloudflare Tunnel for public internet access.

    Cloudflared is free, requires no account, and creates a temporary
    public URL like https://example-random.trycloudflare.com that
    tunnels directly to localhost on the given port.

    Returns the subprocess handle, or None if cloudflared isn't installed.
    """
    import subprocess
    try:
        proc = subprocess.Popen(  # pylint: disable=consider-using-with
            ["cloudflared", "tunnel", "--url", f"http://127.0.0.1:{port}"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        return proc
    except FileNotFoundError:
        return None


def _extract_tunnel_url(proc: subprocess.Popen, timeout: float = 15.0) -> str | None:  # type: ignore[valid-type]
    """Read cloudflared stdout until the tunnel URL appears, then return it."""
    import re
    import time
    deadline = time.monotonic() + timeout
    # cloudflared prints lines like:
    # 2024-01-01T12:00:00Z INF +--------------------------------------------------------------------------------------------+
    # 2024-01-01T12:00:00Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
    # 2024-01-01T12:00:00Z INF |  https://example-random.trycloudflare.com                                                  |
    # 2024-01-01T12:00:00Z INF +--------------------------------------------------------------------------------------------+
    url_pattern = re.compile(r"https://[a-z0-9-]+\.trycloudflare\.com")
    try:
        while time.monotonic() < deadline:
            line = proc.stdout.readline()
            if not line:
                time.sleep(0.1)
                continue
            print(f"  [cloudflared] {line.rstrip()}")
            match = url_pattern.search(line)
            if match:
                return match.group(0)
    except Exception:
        pass
    return None


def cmd_serve(args: argparse.Namespace) -> int:
    """Start the uvicorn server with environment-aware defaults."""
    import uvicorn

    env = check_environment()
    dotenv = _find_env_file(env)

    if dotenv:
        os.environ.setdefault("TRAVEL_ENV_PATH", str(dotenv))
        print(f"✓ Using config: {dotenv}")

    host = args.host or os.getenv("TRAVEL_HOST", "0.0.0.0")
    port = args.port or int(os.getenv("TRAVEL_PORT", "8000"))
    reload = args.reload if args.reload is not None else os.getenv("ENVIRONMENT", "") == "development"
    use_tunnel = args.tunnel

    # Detect LAN IP for shareable beta-testing URL
    lan_ip = _detect_lan_ip()

    print(_ASCII_LOGO)
    print(f"  Host:       {host}")
    print(f"  Port:       {port}")
    print(f"  Reload:     {reload}")
    if lan_ip and host in ("0.0.0.0", ""):
        print(f"  Local:      http://127.0.0.1:{port}")
        print(f"  Network:    http://{lan_ip}:{port}  ← local LAN only")
        print(f"  API Docs:   http://{lan_ip}:{port}/docs")
    else:
        print(f"  UI:         http://{host}:{port}")
        print(f"  API Docs:   http://{host}:{port}/docs")
    print(f"  Health:     http://{host}:{port}/health")
    print()

    # Public tunnel via Cloudflare (for out-of-state beta testers)
    tunnel_proc = None
    if use_tunnel:
        tunnel_proc = _start_cloudflare_tunnel(port)
        if tunnel_proc is None:
            print("  ✗ cloudflared not found. Install it to create a public tunnel:")
            print("    Linux/WSL:  curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o ~/.local/bin/cloudflared && chmod +x ~/.local/bin/cloudflared")
            print("    macOS:      brew install cloudflared")
            print("    Windows:    winget install Cloudflare.cloudflared")
            print()
            print("  Continuing without tunnel — LAN-only mode.")
            print()
        else:
            print("  🌐 Creating public tunnel (Cloudflare) — this may take a few seconds...")
            print()
            tunnel_url = _extract_tunnel_url(tunnel_proc)
            if tunnel_url:
                print()
                print("  ╔══════════════════════════════════════════════════════════════╗")
                print("  ║  🌐 PUBLIC URL (send this to your son!)                     ║")
                print(f"  ║  {tunnel_url:<58s} ║")
                print("  ║                                                            ║")
                print(f"  ║  API Docs:  {tunnel_url}/docs{' ' * (58 - len(tunnel_url + '/docs'))}║")
                print("  ╚══════════════════════════════════════════════════════════════╝")
                print()
                print("  ⚠ This tunnel is temporary — it closes when you stop the server.")
                print("  ⚠ Run 'plan-it serve --tunnel' each time to get a new URL.")
                print()

    # WSL-specific guidance for Windows Firewall
    if env.system == "linux" and "microsoft" in os.uname().release.lower():
        print("  ⚠ WSL detected — to make this accessible from your LAN:")
        print("    1. Open Windows Firewall: inbound rule for TCP port", port)
        print("    2. Or use: netsh interface portproxy add v4tov4 \\")
        print(f"         listenport={port} listenaddress=0.0.0.0 connectport={port} connectaddress=$(wsl hostname -I)")
        print()

    # On Android (Termux) and iOS (iSH), bind to localhost by default
    if env.system in ("android", "ios") and host == "0.0.0.0":
        logger.warning("On %s, binding to 0.0.0.0 may not work. Use 127.0.0.1 for local access.", env.system)

    uvicorn.run(
        "app.main:app",
        host=host,
        port=port,
        reload=reload,
        log_level=args.log_level or "info",
    )
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    """Run environment diagnostics."""
    env = check_environment()
    print(_ASCII_LOGO)
    print(format_env_report(env))

    dotenv = _find_env_file(env)
    if dotenv:
        print(f"\n✓ Config file: {dotenv}")
    else:
        print("\n⚠ No .env file found. Run 'plan-it init' to bootstrap.")

    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    """Full diagnostic: environment, Python, dependencies, and network."""
    import urllib.request

    env = check_environment()
    print(_ASCII_LOGO)
    print("Running full diagnostics...\n")
    print(format_env_report(env))

    # Python packages
    print("\n── Python Packages ──")
    deps = ["fastapi", "uvicorn", "pydantic", "slowapi", "dotenv", "ddgs"]
    all_ok = True
    for dep in deps:
        try:
            __import__(dep.replace("-", "_"))
            print(f"  ✓ {dep}")
        except ImportError:
            print(f"  ✗ {dep} — NOT INSTALLED")
            all_ok = False

    # Network
    print("\n── Network ──")
    for url, label in [
        ("https://duckduckgo.com", "DuckDuckGo (search)"),
        ("https://pypi.org", "PyPI"),
    ]:
        try:
            req = urllib.request.Request(url, method="HEAD")
            with urllib.request.urlopen(req, timeout=5):
                pass
            print(f"  ✓ {label} — reachable")
        except Exception:
            print(f"  ✗ {label} — unreachable")
            all_ok = False

    # App status
    print("\n── App Status ──")
    dotenv = _find_env_file(env)
    if dotenv:
        print(f"  ✓ Config file: {dotenv}")
    else:
        print("  ℹ No config file — app uses defaults")

    print("\n  ℹ No API keys required. The app uses DuckDuckGo")
    print("    for web research and runs completely self-contained.")

    print()
    if all_ok:
        print("✓ All diagnostics passed. Run 'plan-it serve' to start.")
    else:
        print("⚠ Some checks failed. Run 'plan-it init' to re-bootstrap, then fix the issues above.")
    return 0 if all_ok else 1


def main() -> None:
    """Main CLI dispatcher."""
    parser = argparse.ArgumentParser(
        prog="plan-it",
        description="Plan-It — AI-powered itinerary builder",
    )
    sub = parser.add_subparsers(dest="command", title="commands")

    # plan-it init
    p_init = sub.add_parser("init", help="Bootstrap environment and create .env file")
    p_init.set_defaults(func=cmd_init)

    # plan-it serve
    p_serve = sub.add_parser("serve", help="Start the API server")
    p_serve.add_argument("--host", help="Bind address (default: 0.0.0.0)")
    p_serve.add_argument("--port", type=int, help="Port (default: 8000)")
    p_serve.add_argument("--reload", action="store_true", default=None, help="Enable auto-reload")
    p_serve.add_argument("--no-reload", action="store_false", dest="reload", help="Disable auto-reload")
    p_serve.add_argument("--tunnel", action="store_true", default=False, help="Create a public Cloudflare Tunnel for out-of-state sharing")
    p_serve.add_argument("--log-level", choices=["critical", "error", "warning", "info", "debug"], default="info")
    p_serve.set_defaults(func=cmd_serve)

    # plan-it check
    p_check = sub.add_parser("check", help="Print environment info")
    p_check.set_defaults(func=cmd_check)

    # plan-it doctor
    p_doctor = sub.add_parser("doctor", help="Full diagnostics (env, deps, network, API key)")
    p_doctor.set_defaults(func=cmd_doctor)

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    sys.exit(args.func(args))


if __name__ == "__main__":
    main()
